# This file was generated by GoReleaser. DO NOT EDIT.
cask "wootctl-cli" do
  version "0.5.2"

  on_macos do
    on_arm do
      sha256 "fe95fc73f522b8675d4d6850ae4faffe7b850821c58c5156062bafd1ce4a7f97"
      url "https://github.com/jjuanrivvera/wootctl/releases/download/v#{version}/wootctl_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "90c3df223392272f507fb11396176e654ef4a32a86ba10570ee3f791b1a881d9"
      url "https://github.com/jjuanrivvera/wootctl/releases/download/v#{version}/wootctl_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "06a574a19fa2a760a15a0db14fc1b115355f8b697c4b4bbbde012a98e517f2d4"
      url "https://github.com/jjuanrivvera/wootctl/releases/download/v#{version}/wootctl_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "41e18b453d9b9f4dfb0c2c80fd54996fb6041941eed97038c5b33afb9f1065b4"
      url "https://github.com/jjuanrivvera/wootctl/releases/download/v#{version}/wootctl_#{version}_linux_amd64.tar.gz"
    end
  end

  name "wootctl-cli"
  desc ""
  homepage "https://github.com/jjuanrivvera/wootctl"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "wootctl"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/wootctl"]
  end

  # No zap stanza required
end
