# This file was generated by GoReleaser. DO NOT EDIT.
cask "wootctl-cli" do
  version "0.5.1"

  on_macos do
    on_arm do
      sha256 "ec13082e7327db309bddb931c24902d79f878fe2e580d1eb39b5b8b7ac17d702"
      url "https://github.com/jjuanrivvera/wootctl/releases/download/v#{version}/wootctl_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "9fa7dbb7699b6a1b40f5f97fcca435b41ad1c289243aabecbb11c19075aab60d"
      url "https://github.com/jjuanrivvera/wootctl/releases/download/v#{version}/wootctl_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "b05e77570e175831f7a810c6a19128a61dc810e9d219511465ecbb03c4c886e9"
      url "https://github.com/jjuanrivvera/wootctl/releases/download/v#{version}/wootctl_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "337ef11870daeee29dfd9531a72188b3898c0f48abcb6536efb8ec773f96ab65"
      url "https://github.com/jjuanrivvera/wootctl/releases/download/v#{version}/wootctl_#{version}_linux_amd64.tar.gz"
    end
  end

  name "wootctl-cli"
  desc ""
  homepage "https://github.com/jjuanrivvera/wootctl"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "wootctl"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/wootctl"]
  end

  # No zap stanza required
end
