# This file was generated by GoReleaser. DO NOT EDIT.
cask "wootctl-cli" do
  version "0.5.0"

  on_macos do
    on_arm do
      sha256 "efdd18140dab696cbf1ced44c304c9506f46e92c694d0fa4f33297e17e59098a"
      url "https://github.com/jjuanrivvera/wootctl/releases/download/v#{version}/wootctl_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "91e24827bc0883173a948ea1d2625fd2b53e0909931666a8358bca30ba5e9507"
      url "https://github.com/jjuanrivvera/wootctl/releases/download/v#{version}/wootctl_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "ae4dc34e49b42aac30026927accc930561939ab0c7d34dda3a97b6364ede2b03"
      url "https://github.com/jjuanrivvera/wootctl/releases/download/v#{version}/wootctl_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "2895512b965de5c70572931e7ef916604778622baa6c0932d0acb60172e56167"
      url "https://github.com/jjuanrivvera/wootctl/releases/download/v#{version}/wootctl_#{version}_linux_amd64.tar.gz"
    end
  end

  name "wootctl-cli"
  desc ""
  homepage "https://github.com/jjuanrivvera/wootctl"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "wootctl"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/wootctl"]
  end

  # No zap stanza required
end
